web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from .import views


urlpatterns = [
  path('', views.home, name='home'),
  path('about_us/', views.about_us, name='about_us'), 
  path('vision_and_mission/', views.vision_and_mission, name='vision_and_mission'),  
  path('contact_us/', views.contact_us, name='contact_us'), 
  path('why_choose_us/', views.why_choose_us, name='why_choose_us'),
  path('form_submit/', views.form_submit, name='form_submit'),
  path('thank_you/', views.thank_you, name='thank_you'),
  path('our_services/<slug:cat>/', views.our_services, name='our_services'), 
    
]

webapp/models.py
from django.db import models

# Create your models here.

from django.db import models

class navbar(models.Model):
    menu = models.CharField(max_length=100)
    status = models.IntegerField(default=1)

webapp/models/category.py
from django.db import models

# Create your models here.

from django.db import models

class category(models.Model):
    cat_name = models.CharField(max_length=100)
    status = models.IntegerField(default=1)

    def __str__(self):

        return self.cat_name

    @staticmethod
    def get_categorty():
        return category.objects.all()    

webapp/models/enquiry.py
from django.db import models

# Create your models here.

from django.db import models

class enquiry(models.Model):
    name = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    mssage = models.TextField()
    status = models.IntegerField(default=1)

webapp/models/models.py
from django.db import models
from .category import category
# Create your models here.

from django.db import models

class navbar(models.Model):
    menu = models.CharField(max_length=100)
    category = models.ForeignKey(category, default=None,on_delete=models.CASCADE)
    menu_slug = models.SlugField(max_length = 200,default=None)
    status = models.IntegerField(default=1)

    def __str__(self):

        return self.menu

webapp/models/pages.py
from django.db import models
from .models import navbar

# Create your models here.

from django.db import models

class pages(models.Model):
    page=models.TextField()
    menu = models.ForeignKey(navbar, on_delete=models.CASCADE)
    pic=models.ImageField(upload_to='upload_images/')
    status = models.IntegerField(default=1)

webapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from .models import navbar,pages,category,enquiry
from django.core.mail import BadHeaderError, send_mail
# Create your views here.

def home(request):
    return render(request,'webhtml/index.html')
   # return HttpResponse('page')

def about_us(request):
    return render(request,'webhtml/about.html')
   
def vision_and_mission(request):
    return render(request,'webhtml/vision-mission.html')

def contact_us(request):
    return render(request,'webhtml/contact.html')

def why_choose_us(request):
    return render(request,'webhtml/why-choose-us.html')

def thank_you(request):
    return render(request,'webhtml/thank_you.html')

def our_services(request,cat):
    pid=navbar.objects.filter(menu_slug=cat)
    all_entries=category.get_categorty()
    for ids in pid:
        data=pages.objects.filter(menu_id=ids.id)
        for value in data:
            content={
                'text':value.page,
                'imgs':value.pic,
                'title':ids.menu,
                'menu':all_entries,
            }
    
    return render(request,'webhtml/service.html',content)


def form_submit(request):

    if request.method =="POST":
        name = request.POST.get('name')
        subject = request.POST.get('subject')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        mssage = request.POST.get('mssage')
        enquiry.objects.create(name=name,subject=subject,email=email,phone=phone,mssage=mssage)
        return redirect('/thank_you/')
        
        

templates/webhtml/P_SIR/basic.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Solutons a Corporate Category Bootstrap Responsive Website Template - Home : W3Layouts</title>
  <link href="//fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap" rel="stylesheet">
  <link href="//fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{%  static 'webhtml/assets/css/style-starter.css' %}">
</head>

<body>
<header class="w3l-header">
	<nav class="navbar navbar-expand-lg navbar-light fill px-lg-0 py-0 px-3">
		<div class="container">
			<a class="navbar-brand" href="/">
				<span class="fa fa-globe"></span> Solutions <span class="logo">Web Design Agency</span></a>
			<button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
				data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<!-- <span class="navbar-toggler-icon"></span> -->
				<span class="fa icon-expand fa-bars"></span>
				<span class="fa icon-close fa-times"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item active">
						<a class="nav-link" href="/">Home</a>
					</li>
					<li class="nav-item @@about__active about-item">
						<a class="nav-link" href="#">Company</a>
                        <ul class="dropdown-menu-sub">
                          <li><a class="dropdown-item" href="about.php">About us</a></li>
                          <li><a class="dropdown-item" href="vision-mission.php">Vision & Mission</a></li>
                          <li><a class="dropdown-item" href="why-choose-us.php">Why Choose us</a></li>
                          <li><a class="dropdown-item" href="career-with-us.php">Career With us</a></li>
                        </ul>
					</li>
                    <li class="nav-item @@about__active service-item">
                        <a class="nav-link" href="#">Service</a>
                        <ul class="dropdown-menu-sub mega_menu">
                          <div class="row">
                              <div class="col-sm-3">
                                  <ul>
                                    <h5>Web Design</h5>
                                      <li><a href="static-web-desgin.php" class="dropdown-item">Static Web Design</a></li>
                                      <li><a href="responisve-web-desgin.php" class="dropdown-item">Responsive Web Design</a></li>
                                      <li><a href="psd-to-html.php" class="dropdown-item">PSD To HTML</a></li>
                                      <li><a href="website-maintenance.php" class="dropdown-item">Website Maintenance</a></li>
                                    </ul>
                              </div>
                              <div class="col-sm-3">
                                  <ul>
                                    <h5>Degital Marketing</h5>
                                      <li><a href="seo-service.php" class="dropdown-item">SEO Services</a></li>
                                      <li><a href="social-media-marketing.php" class="dropdown-item">Social Media Marketing</a></li>
                                      <li><a href="google-awards.php" class="dropdown-item">Google Adwords (PPC)</a></li>
                                      <li><a href="bulk-sms-service.php" class="dropdown-item">Bulk SMS Services</a></li>
                                  </ul>
                              </div>
                              <div class="col-sm-3">
                                  <ul>
                                    <h5>Graphic Design</h5>
                                      <li><a href="logo-desgin.php" class="dropdown-item">Logo Design</a></li>
                                      <li><a href="#web-layout-design.php" class="dropdown-item">Web Layout Design</a></li>
                                      <li><a href="#" class="dropdown-item">Brochure Design</a></li>
                                      <li><a href="#" class="dropdown-item">Corporate Design</a></li>
                                  </ul>
                              </div>
                              <div class="col-sm-3">
                                  <ul>
                                    <h5>Web Development</h5>
                                      <li><a href="#" class="dropdown-item">PSD To WordPress</a></li>
                                      <li><a href="#" class="dropdown-item">E-Commerce Website</a></li>
                                  </ul>
                              </div>
                              <div class="col-sm-3">
                                  <ul>
                                    <h5>Web Start Up</h5>
                                      <li><a href="#" class="dropdown-item">Domain Registration</a></li>
                                      <li><a href="#" class="dropdown-item">Web Hosting</a></li>
                                      <li><a href="#" class="dropdown-item">E-Mail / SSL Services</a></li>
                                  </ul>
                              </div>
                              <div class="col-sm-3">
                                  <ul>
                                    <h5>Content Writing</h5>
                                      <li><a href="#" class="dropdown-item">Hindi Content</a></li>
                                      <li><a href="#" class="dropdown-item">English Content</a></li>
                                  </ul>
                              </div>
                          </div>
                        </ul>
                    </li>
					<li class="nav-item @@contact__active">
						<a class="nav-link" href="contact.php">Contact</a>
					</li>
				</ul>
				<div class="ml-lg-3">
					<a href="#url" class="btn btn-style btn-effect">Get Started</a>
				</div>
			</div>
		</div>
	</nav>
</header>

<style>
    
.backleftimg:before {
  content: "";
  position: absolute;
  left: 0;
  top: 100px;
  width: 100%;
  height: 100%;
  background: url(./assets/images/shap1.png);
  background-position: center;
  background-size: contain;
  background-repeat: no-repeat;
}
</style>
{% block body %} {% endblock %}

<!-- //banner section -->




  
  <section class="w3l-footer-29-main w3l-copyright">
    <div class="container">
      <div class="row bottom-copies">
        <p class="col-lg-8 copy-footer-29">© 2020 Solutions. All rights reserved.  Design by <a href="https://w3layouts.com/" target="_blank">
          W3Layouts</a></p>
  
        <div class="col-lg-4 main-social-footer-29">
          <a href="#facebook" class="facebook"><span class="fa fa-facebook"></span></a>
          <a href="#twitter" class="twitter"><span class="fa fa-twitter"></span></a>
          <a href="#instagram" class="instagram"><span class="fa fa-instagram"></span></a>
          <a href="#linkedin" class="linkedin"><span class="fa fa-linkedin"></span></a>
        </div>
  
      </div>
    </div>
  
    <!-- move top -->
    <button onclick="topFunction()" id="movetop" title="Go to top">
      &#10548;
    </button>
    <script>
      // When the user scrolls down 20px from the top of the document, show the button
      window.onscroll = function () {
        scrollFunction()
      };
  
      function scrollFunction() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
          document.getElementById("movetop").style.display = "block";
        } else {
          document.getElementById("movetop").style.display = "none";
        }
      }
  
      // When the user clicks on the button, scroll to the top of the document
      function topFunction() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
      }
    </script>
    <!-- /move top -->
  </section>
  <!-- //copyright -->
  
  
  <!-- Template JavaScript -->
  
  <script src="{%  static 'webhtml/assets/js/jquery-3.3.1.min.js' %}" "></script>
  
  <!-- script for customers -->
  <script src="{%  static 'webhtml/assets/js/owl.carousel.js' %}"></script>
  <script>
    $(document).ready(function () {
      $('.owl-three').owlCarousel({
        loop: true,
        margin: 0,
        nav: false,
        responsiveClass: true,
        autoplay: true,
        autoplayTimeout: 5000,
        autoplaySpeed: 1000,
        autoplayHoverPause: false,
        responsive: {
          0: {
            items: 3,
            nav: false
          },
          480: {
            items: 3,
            nav: false
          },
          667: {
            items: 4,
            nav: false
          },
          800: {
            items: 5,
            nav: false
          },
          1280: {
            items: 6,
            nav: false
          }
        }
      })
    })
  </script>
  <!-- //script for customers -->
  
  <!-- for tesimonials carousel slider -->
  <script>
      $(document).ready(function () {
          $("#owl-demo1").owlCarousel({
              loop: true,
              margin:20,
              responsiveClass: true,
              responsive: {
                  0: {
                      items:1,
                      nav: true
                  },
                  736: {
                      items: 2,
                      nav: false
                  },
                  1000: {
                      items: 2,
                      nav: true,
                      loop: false
                  }
              }
          })
      })
  </script>
  <!-- //script -->
  
  <!-- script for teams -->
  <script>
    $(document).ready(function () {
      $('.owl-carousel').owlCarousel({
        loop: true,
        margin: 0,
        responsiveClass: true,
        responsive: {
          0: {
            items: 1,
            nav: true
          },
          415: {
            items: 2,
            nav: true,
            margin: 20
          },
          667: {
            items: 3,
            nav: true,
            margin: 20
          },
          1000: {
            items: 4,
            nav: true,
            loop: true,
            margin: 25
          }
        }
      })
    })
  </script>
  <!-- //script for teams-->
  
  <!-- magnific popup -->
  <script src="{%  static 'webhtml/assets/js/jquery.magnific-popup.min.js' %}"></script>
  <script>
    $(document).ready(function () {
      $('.popup-with-zoom-anim').magnificPopup({
        type: 'inline',
  
        fixedContentPos: false,
        fixedBgPos: true,
  
        overflowY: 'auto',
  
        closeBtnInside: true,
        preloader: false,
  
        midClick: true,
        removalDelay: 300,
        mainClass: 'my-mfp-zoom-in'
      });
  
      $('.popup-with-move-anim').magnificPopup({
        type: 'inline',
  
        fixedContentPos: false,
        fixedBgPos: true,
  
        overflowY: 'auto',
  
        closeBtnInside: true,
        preloader: false,
  
        midClick: true,
        removalDelay: 300,
        mainClass: 'my-mfp-slide-bottom'
      });
    });
  </script>
  <!-- magnific popup -->
  
  <!-- stats number counter-->
  <script src="{%  static 'webhtml/assets/js/jquery.waypoints.min.js' %}" "></script>
  <script src="{%  static 'webhtml/assets/js/jquery.countup.js' %}" "></script>
  <script>
    $('.counter').countUp();
  </script>
  <!-- //stats number counter -->
  
  <!-- disable body scroll which navbar is in active -->
  <script>
    $(function () {
      $('.navbar-toggler').click(function () {
        $('body').toggleClass('noscroll');
      })
    });
  </script>
  <!-- disable body scroll which navbar is in active -->
  
  <script src="{%  static 'webhtml/assets/js/bootstrap.min.js' %}"></script>
  
  </body>
  
  </html>

templates/webhtml/P_SIR/bulk-sms-service.html
<?php include 'header.php'; ?>
<section class="bradcrumbsec">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>SEO SERVICE</h2>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li> | SEO SERVICE</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="static_web_sec py-5 mt-4">
	<div class="container position-relative">
		<div class="row">
			<div class="col-lg-4 mb-5">
                <div class="static_leftbox">
                    <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="card-head" id="headingOne">
                        <h2 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                         Web Design
                        </h2>
                        </div>
                        <div id="collapseOne" class="collapse " aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body pt-2">
                            <li><a href="static-web-desgin.php" class="dropdown-item ">Static Web Design</a></li>
                            <li><a href="responisve-web-desgin.php" class="dropdown-item ">Responsive Web Design</a></li>
                            <li><a href="psd-to-html.php" class="dropdown-item ">PSD To HTML</a></li>
                            <li><a href="website-maintenance.php" class="dropdown-item ">Website Maintenance</a></li>
                        </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-head" id="headingTwo">
                        <h2 class="mb-0 " data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
                        Degital Marketing
                        </h2>
                        </div>
                        <div id="collapseTwo" class="collapse " aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="card-body pt-2">
                            <li><a href="seo-service.php" class="dropdown-item">SEO Services</a></li>
                            <li><a href="social-media-marketing.php" class="dropdown-item ">Social Media Marketing</a></li>
                            <li><a href="google-awards.php" class="dropdown-item ">Google Adwords (PPC)</a></li>
                            <li><a href="bulk-sms-service.php" class="dropdown-item active">Bulk SMS Services</a></li>
                        </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-head" id="headingThree">
                        <h2 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Graphic Design
                        </h2>
                        </div>
                        <div id="collapseThree" class="collapse show" aria-labelledby="headingThree" data-parent="#accordionExample">
                        <div class="card-body pt-2">
                            <li><a href="#" class="dropdown-item">Logo Design</a></li>
                            <li><a href="#" class="dropdown-item">Web Layout Design</a></li>
                            <li><a href="#" class="dropdown-item">Brochure Design</a></li>
                            <li><a href="#" class="dropdown-item">Corporate Design</a></li>
                        </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-head" id="headingfour">
                        <h2 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapsefour" aria-expanded="false" aria-controls="collapsefour">
                        Web Development
                        </h2>
                        </div>
                        <div id="collapsefour" class="collapse" aria-labelledby="headingfour" data-parent="#accordionExample">
                            <div class="card-body pt-2">
                                <li><a href="#" class="dropdown-item">PSD To WordPress</a></li>
                                <li><a href="#" class="dropdown-item">E-Commerce Website</a></li>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-head" id="headingFive">
                        <h2 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                        Web Start Up
                        </h2>
                        </div>
                        <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
                            <div class="card-body pt-2">
                                <li><a href="#" class="dropdown-item">Domain Registration</a></li>
                                <li><a href="#" class="dropdown-item">Web Hosting</a></li>
                                <li><a href="#" class="dropdown-item">E-Mail / SSL Services</a></li>
                            </div>
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-head" id="headingFive">
                        <h2 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                        Content Writing
                        </h2>
                        </div>
                        <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
                            <div class="card-body pt-2">
                                <li><a href="#" class="dropdown-item">Hindi Content</a></li>
                                <li><a href="#" class="dropdown-item">English Content</a></li>
                            </div>
                        </div>
                    </div>
                    </div>
                    <div class="bgcontact" style="background: url(assets/images/bg_contact.jpg);">
                        <div class="position-relative text-white">
                        <h3 class="text-white mb-4 font-weight-bold">Need any help?</h3>
                        <p class="text-white mb-3" style="font-size: 15px;">We are here to help our customer any time. You can call on 24/7 To Answer Your Question.</p>
                        <a class="text-white" href="tel: 1800855800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                        </svg> 1800855800
                        </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 mb-5">
                <div class="static-rightbox">
                    <div class="static_top_img">
                        <img src="assets/images/1.jpg" alt="Logo Design" width="100%">
                    </div>
                    <h1 class="my-4">Creative & Digital ideas</h1>
                    <p>We denounce with righteous indige nation and dislike men who are so beguiled and demo realized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue cannot foresee. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled data structures manages data in technology.</p>
                    <p>Nam libero tempore, cum soluta nobis est elig endi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repelle ndus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.</p>
                    <p>Nam libero tempore, cum soluta nobis est elig endi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repelle ndus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias. consequatur aut perferendis doloribus asperiores repellat. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains. pleasures have to be repudiated and annoyances accepted.</p>
                </div>
            </div>
		</div>
	</div>
</section>
  
<section class="bg_contact_service" style="background: url(assets/images/bg_service.png);">
<div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>WE ARE A FULL SERVICE</h1>
                <p>With such a primary emphasis on Open Source Technology and Networks, Softrab Solutions provides online and smartphone based app development services.</p>
                <a href="contact.php" class="text-white font-weight-bold mt-3">Contact Us</a>
            </div>
        </div>
    </div>
</section>

<?php include 'footer.php'; ?>

templates/webhtml/navbar.html
{% load poll_extras %}
<li class="nav-item @@about__active service-item">
    <a class="nav-link" href="#">Service</a>
    <ul class="dropdown-menu-sub mega_menu">
      <div class="row">
        {% for cat in links %}
          <div class="col-sm-3">
              <ul>
                <h5>  {{ cat.cat_name }} </h5>
                
                {% for sub in cat.navbar_set.all %}
              
                  <li><a href="/our_services/{{ sub.menu_slug }}" class="dropdown-item">{{ sub.menu }}</a></li>
              
                
                  {% endfor %}
                  
                </ul>
          </div>
          {% endfor %}
         
          
     
      </div>
    </ul>
</li>

templates/webhtml/service.html
{% extends "webhtml/basic.html" %}
{% load static %}
{% block title %} About Us {% endblock %}
{% block body %} 
<section class="bradcrumbsec">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h2>SEO SERVICE</h2>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li> | {{ title }}</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section class="static_web_sec py-5 mt-4">
	<div class="container position-relative">
		<div class="row">
			<div class="col-lg-4 mb-5">
                <div class="static_leftbox">
                    <div class="accordion" id="accordionExample">
                        {% for cat in menu %}
                    <div class="card">
                        <div class="card-head" id="heading{{ cat.id }}">
                        <h2 class="mb-0 collapsed" data-toggle="collapse" data-target="#collapse{{ cat.id }}" aria-expanded="false" aria-controls="collapse{{ cat.id }}">
                        {{ cat.cat_name }}
                        </h2>
                        </div>
                        <div id="collapse{{ cat.id }}" class="collapse " aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body pt-2">
                            {% for sub in cat.navbar_set.all %}
                            <li><a href="/our_services/{{ sub.menu_slug }}" class="dropdown-item ">Static Web Design</a></li>
                            {% endfor %}
                        </div>
                        </div>
                    </div>
                    {% endfor %}
                   
                  
                
                    </div>
                    <div class="bgcontact" style="background: url(assets/images/bg_contact.jpg);">
                        <div class="position-relative text-white">
                        <h3 class="text-white mb-4 font-weight-bold">Need any help?</h3>
                        <p class="text-white mb-3" style="font-size: 15px;">We are here to help our customer any time. You can call on 24/7 To Answer Your Question.</p>
                        <a class="text-white" href="tel: 1800855800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                        </svg> 1800855800
                        </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 mb-5">
                <div class="static-rightbox">
                    <div class="static_top_img">
                        <img src="{{ imgs.url }}" alt="Logo Design" width="100%">
                    </div>
                    {{ text }}
                </div>
            </div>
		</div>
	</div>
</section>
  
<section class="bg_contact_service" style="background: url(assets/images/bg_service.png);">
<div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>WE ARE A FULL SERVICE</h1>
                <p>With such a primary emphasis on Open Source Technology and Networks, Softrab Solutions provides online and smartphone based app development services.</p>
                <a href="/contact_us" class="text-white font-weight-bold mt-3">Contact Us</a>
            </div>
        </div>
    </div>
</section>

{% endblock %}